version: "3.3"
services:
  scrapy:
    build:
        context: ./scrapy/
        dockerfile: ../.docker/scrapy/Dockerfile
    volumes:
        - ./scrapy:/code

  web:
    build:
      context: ./
      dockerfile: .docker/flask/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/code
