version: "3.3"
services:
  scrapy:
    build:
      context: ./scrapy/
      dockerfile: ../.docker/scrapy/Dockerfile
    volumes:
      - ./scrapy:/code

  web:
    build:
      context: ./
      dockerfile: .docker/flask/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/code

  mongo:
    image: mongo
    restart: always
    ports:
      - 8099:27017
    environment:
      MONGO_INITDB_DATABASE: movies
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
